export const READBOOSTER_CONTENT_BLOCK_ATTRIBUTE = "data-readbooster-content-block";
export const DOCUMENT_CONTENT_BLOCK_KIND = "document";
export const DOCUMENT_CONTENT_BLOCK_SELECTOR = `[${READBOOSTER_CONTENT_BLOCK_ATTRIBUTE}="${DOCUMENT_CONTENT_BLOCK_KIND}"]`;
